@Logging_HostAddress = http://localhost:5151

GET {{Logging_HostAddress}}/pokemon
Accept: application/json

###
GET {{Logging_HostAddress}}/pokemon/114
Accept: application/json
### Not found
GET {{Logging_HostAddress}}/pokemon/1114
Accept: application/json