<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>d53a934f-29c9-4ae4-a7f6-6fb68417ac6f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.3.1" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.3.1" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="9.3.2" />
    <PackageReference Include="Aspire.Microsoft.Data.SqlClient" Version="9.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logging.WebApp\ProductStore.WebApp.csproj" />
    <ProjectReference Include="..\Logging\ProductStore.WebApi.csproj" />
    <ProjectReference Include="..\ProductStore.Loader\ProductStore.Loader.csproj" />
  </ItemGroup>

</Project>
