@ApiService_HostAddress = http://localhost:5355

GET {{ApiService_HostAddress}}/products/
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/products/
Accept: application/json
###

DELETE {{ApiService_HostAddress}}/api/products/1
Accept: application/json
###