<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logging.Data.Api\ProductStore.Contracts.csproj" />
    <ProjectReference Include="..\ProductStore.ServiceDefaults\ProductStore.ServiceDefaults.csproj" />
    <ProjectReference Include="..\ProductStore.WebApi.Client\ProductStore.WebApi.Client.csproj" />
  </ItemGroup>

</Project>
